spring:
  application:
    name: postgres_sample
  jpa:
    database: postgresql
    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: bergen
    password: 123
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false